### ISSUE TITLE
Line No in document feature

### ISSUE THREAD

**Issue by juasanri** [hougaard/Simple-Object-Designer#294]
Hello,

When I create a new feature that is document, I am not able to show in the Web API the LineNo of the lines:

![image](https://github.com/hougaard/Simple-Object-Designer/assets/99739571/50fb8e6f-e0ed-4325-94a8-1a972f231bd2)

The field LineNo (99999) is not available. I would like to have it as I want to add lines through Power Automate. Currently, I can only add one line, because LineNo is never increased.

Would it be possible?

Thanks

**Comment by hougaard** [comment]
Yes, it's coming, very soon!

**Comment by hougaard** [comment]
Fixed in version 9.0.0.344.

**Comment by hougaard** [comment]
The field should be available in API calls now, if published with the latest version of SOD.

**Comment by juasanri** [comment]
It is published with the latest version, but still not available in Power
Automate:

[image: image.png]

Thanks

**Comment by hougaard** [comment]
I can't see the screen (you gotta log into github and paste it there)... Try sending your app file to support@hougaard.com and I'll check what's going on.

**Comment by juasanri** [comment]
I paste the image here, and will send the app file to your email.

Thank you!

![image](https://github.com/hougaard/Simple-Object-Designer/assets/99739571/d043e39d-4d42-421f-8500-c23e1cb5fe00)

**Comment by hougaard** [comment]
Found it, please try with SOD 9.0.0.345.

**Comment by juasanri** [comment]
Fixed!

Thank you!
